In [1]:
# Dependencies
import requests
import csv
import json
import pandas as pd
from pathlib import Path

In [2]:
#read the csvs file into a data frame
state_pro_data= Path('Resources/market_rev_teams_df_FINALSET.csv')
state_pro_df= pd.read_csv(state_pro_data)
state_pro_df

   state_abbr                 state  Teams Count  MLB  NBA  NFL  NHL
0          AK                Alaska            0    0    0    0    0
1          AL               Alabama            0    0    0    0    0
2          AR              Arkansas            0    0    0    0    0
3          AZ               Arizona            4    1    1    1    1
4          CA            California           15    5    4    3    3
5          CO              Colorado            4    1    1    1    1
6          CT           Connecticut            0    0    0    0    0
7          DC  District of Columbia            3    1    1    0    1
8          DE              Delaware            0    0    0    0    0
9          FL               Florida            9    2    2    3    2
10         GA               Georgia            3    1    1    1    0
11         HI                Hawaii            0    0    0    0    0
12         IA                  Iowa            0    0    0    0    0
13         ID                 Idaho            0    0    0    0    0
14         IL              Illinois            5    2    1    1    1
15         IN               Indiana            2    0    1    1    0
16         KS                Kansas            0    0    0    0    0
17         KY              Kentucky            0    0    0    0    0
18         LA             Louisiana            2    0    1    1    0
19         MA         Massachusetts            4    1    1    1    1
20         MD              Maryland            3    1    0    2    0
21         ME                 Maine            0    0    0    0    0
22         MI              Michigan            4    1    1    1    1
23         MN             Minnesota            4    1    1    1    1
24         MO              Missouri            4    2    0    1    1
25         MS           Mississippi            0    0    0    0    0
26         MT               Montana            0    0    0    0    0
27         NC        North Carolina            3    0    1    1    1
28         ND          North Dakota            0    0    0    0    0
29         NE              Nebraska            0    0    0    0    0
30         NH         New Hampshire            0    0    0    0    0
31         NJ            New Jersey            3    0    0    2    1
32         NM            New Mexico            0    0    0    0    0
33         NV                Nevada            2    0    0    1    1
34         NY              New York            8    2    2    1    3
35         OH                  Ohio            6    2    1    2    1
36         OK              Oklahoma            1    0    1    0    0
37         OR                Oregon            1    0    1    0    0
38         PA          Pennsylvania            7    2    1    2    2
39         RI          Rhode Island            0    0    0    0    0
40         SC        South Carolina            0    0    0    0    0
41         SD          South Dakota            0    0    0    0    0
42         TN             Tennessee            3    0    1    1    1
43         TX                 Texas            8    2    3    2    1
44         UT                  Utah            1    0    1    0    0
45         VA              Virginia            0    0    0    0    0
46         VT               Vermont            0    0    0    0    0
47         WA            Washington            3    1    0    1    1
48         WI             Wisconsin            3    1    1    1    0
49         WV         West Virginia            0    0    0    0    0
50         WY               Wyoming            0    0    0    0    0

In [8]:
state_pro_df.to_csv('Resources/pro_team_per_state.csv')

In [9]:
# Function to convert a CSV to JSON
# Takes the file paths as arguments
def make_json(csvFilePath, jsonFilePath):
     
    # create a dictionary
    data = {}
     
    # Open a csv reader called DictReader
    with open(csvFilePath, encoding='utf-8') as csvf:
        csvReader = csv.DictReader(csvf)
         
        # Convert each row into a dictionary
        # and add it to data
        for rows in csvReader:
             
            #primary key
            key = rows['']
            data[key] = rows
 
    # Open a json writer, and use the json.dumps()
    # function to dump data
    with open(jsonFilePath, 'w', encoding='utf-8') as jsonf:
        jsonf.write(json.dumps(data, indent=4))

In [10]:
# Driver Code
 
# Decide the two file paths according to your
# computer system
csvFilePath = r'Resources/pro_team_per_state.csv'
jsonFilePath = r'json/pro_team_per_state.json'

In [11]:
# Call the make_json function
make_json(csvFilePath, jsonFilePath)